-- Generated from AI_Tools_Updated_with_Open_Science.xlsx, sheet: AI Tools
-- Ratings, comments, and use counts are intentionally not seeded.

insert into public.tools (
  id, slug, category, name, best_for, pricing, strengths, caveats, status, website_url, source_url, last_checked, source_type, moderation_status
) values
  ('cfe56ebd-618a-53a1-a088-cf3e7c437663', 'chatgpt-openai', 'General', 'ChatGPT (OpenAI)', 'General Q&A, research, files & creation', 'Free tier + paid plans', 'Broad multimodal assistant; strong for research, analysis, coding, writing, files and image generation.', 'Feature limits vary by plan; verify important factual claims and citations.', 'Current', 'https://chatgpt.com/', 'https://openai.com/chatgpt/pricing', '2026-08-13', 'spreadsheet', 'approved'),
  ('eb510fe0-ebc8-5716-b1af-9d76fb2d73fb', 'claude-anthropic', 'General', 'Claude (Anthropic)', 'Long documents, reasoning & writing', 'Free tier + paid plans', 'Strong long-context work, writing, document analysis, coding and structured reasoning.', 'Plan limits and model availability change over time.', 'Current', 'https://claude.ai/', 'https://www.anthropic.com/pricing', '2026-08-13', 'spreadsheet', 'approved'),
  ('c212d3b4-86a0-5258-81b2-92e2b1fb6b2c', 'gemini-google', 'General', 'Gemini (Google)', 'Google ecosystem & multimodal work', 'Free tier + paid plans', 'Multimodal assistant with strong integration across Google products and research workflows.', 'Best experience may depend on Google account/workspace tier.', 'Current', 'https://gemini.google.com/', 'https://gemini.google.com/', '2026-08-13', 'spreadsheet', 'approved'),
  ('45359627-df14-502f-8b03-4c741e773f87', 'microsoft-copilot', 'General', 'Microsoft Copilot', 'Microsoft 365 & web assistance', 'Free tier + paid plans', 'Useful for web assistance and Microsoft ecosystem workflows.', 'Capabilities differ between consumer Copilot and Microsoft 365 Copilot.', 'Current', 'https://copilot.microsoft.com/', 'https://copilot.microsoft.com/', '2026-08-13', 'spreadsheet', 'approved'),
  ('f1792cc6-e774-5ffc-ba9f-e6415438d18e', 'perplexity', 'Research', 'Perplexity', 'Web research with citations', 'Free tier + paid plans', 'Search-first AI answers with linked sources; useful for quickly surveying a topic.', 'Citations still need checking for support and source quality.', 'Current', 'https://www.perplexity.ai/', 'https://www.perplexity.ai/', '2026-08-13', 'spreadsheet', 'approved'),
  ('ac97448b-3e50-5b7b-8e7a-25e9c364de43', 'undermind', 'Research', 'Undermind', 'Deep literature discovery', 'Freemium / paid options', 'Research-focused discovery designed for deeper literature exploration.', 'More specialized than a general assistant; coverage depends on indexed literature.', 'Current', 'https://undermind.ai/', 'https://undermind.ai/', '2026-08-13', 'spreadsheet', 'approved'),
  ('f4f940fa-cd92-5e27-b012-fe6d4c7c1ff4', 'elicit', 'Research', 'Elicit', 'Literature review & evidence extraction', 'Free tier + paid plans', 'Helps find papers, extract study details and organize evidence for literature reviews.', 'Use the original papers for final interpretation and citation.', 'Current', 'https://elicit.com/', 'https://elicit.com/', '2026-08-13', 'spreadsheet', 'approved'),
  ('e669dc93-0cc6-53dd-957e-d1b9e6c20588', 'scite', 'Research', 'Scite', 'Citation context', 'Free tier + paid plans', 'Shows how papers are cited, including supporting or contrasting citation contexts.', 'Citation labels are aids, not substitutes for reading the citing paper.', 'Current', 'https://scite.ai/', 'https://scite.ai/', '2026-08-13', 'spreadsheet', 'approved'),
  ('60014914-4dde-5ecd-8579-b37157a6f40a', 'semantic-scholar', 'Research', 'Semantic Scholar', 'Academic paper discovery', 'Free', 'Fast academic search with AI-enhanced discovery and paper metadata.', 'Best used as a discovery layer rather than a full literature-review workflow.', 'Current', 'https://www.semanticscholar.org/', 'https://www.semanticscholar.org/', '2026-08-13', 'spreadsheet', 'approved'),
  ('521eee4e-bc7a-5e48-86f8-c9be37adfca0', 'gemini-notebook-formerly-notebooklm', 'Research', 'Gemini Notebook (formerly NotebookLM)', 'Source-grounded research & learning', 'Free / paid tiers vary', 'Builds research notebooks grounded in supplied sources; supports summaries and source-linked exploration.', 'Google renamed NotebookLM to Gemini Notebook in July 2026; feature availability varies by tier.', 'Current', 'https://notebooklm.google.com/', 'https://blog.google/innovation-and-ai/products/gemini-notebook/notebooklm-gemini-notebook/', '2026-08-13', 'spreadsheet', 'approved'),
  ('54bfad78-a120-51a8-aff7-7be7d7770447', 'cursor', 'Coding', 'Cursor', 'AI-native code editor', 'Free tier + paid plans', 'Codebase-aware editing, chat, debugging and agentic coding inside an IDE.', 'Review generated changes and tests; large agent runs can consume plan limits.', 'Current', 'https://www.cursor.com/', 'https://www.cursor.com/', '2026-08-13', 'spreadsheet', 'approved'),
  ('f12c2024-fbca-56fa-8084-06943302077b', 'github-copilot', 'Coding', 'GitHub Copilot', 'IDE pair programming', 'Free tier + paid plans', 'Inline completion, chat and coding assistance integrated with popular IDEs and GitHub.', 'Quality depends on repository context; generated code still needs review and testing.', 'Current', 'https://github.com/features/copilot', 'https://github.com/features/copilot', '2026-08-13', 'spreadsheet', 'approved'),
  ('14f6e89c-185f-5a6e-b160-750ae27cbb49', 'replit-agent', 'Coding', 'Replit Agent', 'Build and deploy apps from prompts', 'Free entry + paid usage', 'Agent can plan, write, debug and deploy applications in Replit''s hosted environment.', 'Replaces the old Ghostwriter branding; more app-building oriented than simple autocomplete.', 'Current', 'https://replit.com/products/agent', 'https://replit.com/blog/ai4all', '2026-08-13', 'spreadsheet', 'approved'),
  ('cf0bab5a-26b5-50d0-960a-6ef5f62f4c91', 'claude-code', 'Coding', 'Claude Code', 'Terminal / codebase agent', 'Included with some Claude plans + usage-based options', 'Agentic coding tool for repository-scale tasks, terminal workflows, debugging and refactoring.', 'Can make broad code changes; use version control and review diffs carefully.', 'Current', 'https://claude.com/product/claude-code', 'https://support.anthropic.com/en/articles/11145838-using-claude-code-with-your-pro-or-max-plan', '2026-08-13', 'spreadsheet', 'approved'),
  ('e56d02b4-3887-54c2-919c-78b0bd03ae30', 'openai-codex', 'Coding', 'OpenAI Codex', 'Software engineering agent', 'Included with eligible ChatGPT plans; limits vary', 'Coding agent for editing repositories, running commands/tests and delegating software tasks.', 'Usage limits and access differ by ChatGPT plan and environment.', 'Current', 'https://openai.com/codex/', 'https://openai.com/codex/', '2026-08-13', 'spreadsheet', 'approved'),
  ('713992e1-ad21-5925-a840-c07aaf71455f', 'midjourney', 'Visual', 'Midjourney', 'Stylized image generation', 'Paid', 'Strong visual style, concept art and high-quality image generation.', 'Less oriented toward document/workflow integration than general assistants.', 'Current', 'https://www.midjourney.com/', 'https://www.midjourney.com/', '2026-08-13', 'spreadsheet', 'approved'),
  ('5865fd27-d106-540a-b6d6-32199598ee24', 'leonardo-ai', 'Visual', 'Leonardo AI', 'Illustration & creative assets', 'Freemium', 'Image generation geared toward creative assets, illustration and iterative design.', 'Credit limits and model options vary by plan.', 'Current', 'https://leonardo.ai/', 'https://leonardo.ai/', '2026-08-13', 'spreadsheet', 'approved'),
  ('38142d76-0969-5c80-9714-0c98ae541dff', 'runway', 'Visual', 'Runway', 'AI video generation & editing', 'Free trial / paid plans', 'AI video generation, editing and effects in a creator-focused workflow.', 'Video generation can be credit-intensive and results may need multiple iterations.', 'Current', 'https://runwayml.com/', 'https://runwayml.com/', '2026-08-13', 'spreadsheet', 'approved'),
  ('3f418018-1ed7-5077-a82f-9d876e776051', 'khanmigo-khan-academy', 'Writing', 'Khanmigo (Khan Academy)', 'Guided tutoring', 'Subscription / eligible access', 'Tutor-style guidance for learning across school subjects with Khan Academy content.', 'Best for guided learning rather than simply producing final answers.', 'Current', 'https://www.khanmigo.ai/', 'https://www.khanmigo.ai/', '2026-08-13', 'spreadsheet', 'approved'),
  ('2ed82276-64d8-5012-9883-1cac222e3993', 'quillbot', 'Writing', 'QuillBot', 'Paraphrasing & rewriting', 'Freemium', 'Paraphrasing, summarization and writing-assistance tools.', 'Overuse can flatten voice; check institutional rules for academic work.', 'Current', 'https://quillbot.com/', 'https://quillbot.com/', '2026-08-13', 'spreadsheet', 'approved'),
  ('77ef1170-a10b-5a8c-8e54-71cbec8fa64a', 'grammarly', 'Writing', 'Grammarly', 'Grammar, tone & clarity', 'Freemium', 'Writing assistance for grammar, tone, clarity and revision.', 'Suggestions are stylistic aids and can occasionally change intended meaning.', 'Current', 'https://www.grammarly.com/', 'https://www.grammarly.com/', '2026-08-13', 'spreadsheet', 'approved'),
  ('8118d59c-fb74-531b-920a-558f38cbe793', 'notion-ai', 'Notes', 'Notion AI', 'Workspace writing & knowledge', 'Paid AI features / plan-dependent', 'AI writing, summarization and knowledge assistance inside Notion workspaces.', 'Most useful when your notes and team knowledge already live in Notion.', 'Current', 'https://www.notion.com/product/ai', 'https://www.notion.com/product/ai', '2026-08-13', 'spreadsheet', 'approved'),
  ('01ebe250-72d3-511d-8400-c2ac11b7b931', 'mem', 'Notes', 'Mem', 'AI-assisted knowledge recall', 'Paid / plan-dependent', 'AI-assisted capture, recall and organization of personal or team knowledge.', 'Value depends on consistent use and how much information is stored in the system.', 'Current', 'https://mem.ai/', 'https://mem.ai/', '2026-08-13', 'spreadsheet', 'approved'),
  ('d36bbb29-7f4b-570b-8076-e1be19e16e3c', 'obsidian-ai-plugins', 'Notes', 'Obsidian + AI plugins', 'Local linked notes + extensible AI', 'Core app free; plugins/services vary', 'Flexible local-first knowledge base with a large plugin ecosystem for AI workflows.', 'AI functionality depends on third-party plugins, model providers and configuration.', 'Current', 'https://obsidian.md/', 'https://obsidian.md/', '2026-08-13', 'spreadsheet', 'approved'),
  ('3d9e71be-1c9a-5e30-a9ed-cb566cc2cf02', 'wolfram-alpha', 'Science', 'Wolfram Alpha', 'Computation & symbolic knowledge', 'Freemium', 'Useful for symbolic math, computation, units, factual scientific queries and verification.', 'Not a general conversational research assistant; input formulation matters.', 'Current', 'https://www.wolframalpha.com/', 'https://www.wolframalpha.com/', '2026-08-13', 'spreadsheet', 'approved'),
  ('1160fabb-207b-59bd-8e53-ab966c6a822a', 'claude-science', 'Science', 'Claude Science', 'Scientific workbench', 'Included with eligible Claude plans', 'Scientific workbench integrating research tools, packages and compute-oriented workflows.', 'Beta product; availability is currently limited to supported plans and platforms.', 'Beta', 'https://claude.com/science', 'https://www.anthropic.com/news/claude-science-ai-workbench', '2026-08-13', 'spreadsheet', 'approved'),
  ('dfe9e003-ca88-5f90-b3d5-373de4ef0916', 'openai-for-science', 'Science', 'OpenAI for Science', 'Scientific research program / workflows', 'Program / initiative, not a standalone app', 'OpenAI initiative focused on applying frontier models and scientific tools to research workflows.', 'Treat this as a science program and set of collaborations, not a separate end-user product.', 'Initiative', 'https://openai.com/index/accelerating-science-gpt-5/', 'https://openai.com/index/accelerating-science-gpt-5/', '2026-08-13', 'spreadsheet', 'approved'),
  ('3ba08bf9-33fe-5003-b3a1-f654471dc183', 'gamma', 'Presentations', 'Gamma', 'AI presentations & documents', 'Freemium', 'Fast generation of presentation-style content and web-native documents.', 'Review structure, factual claims and visual consistency before presenting.', 'Current', 'https://gamma.app/', 'https://gamma.app/', '2026-08-13', 'spreadsheet', 'approved'),
  ('30ff5d15-688b-5bf1-a4ff-043922121bcd', 'canva-magic-studio', 'Presentations', 'Canva Magic Studio', 'Design + AI creation', 'Freemium / paid plans', 'Combines presentation, social, image and design workflows with AI-assisted creation.', 'AI capabilities and export options vary by plan.', 'Current', 'https://www.canva.com/magic-studio/', 'https://www.canva.com/magic-studio/', '2026-08-13', 'spreadsheet', 'approved'),
  ('d7a9cb4c-2dab-5e86-9525-e905452324ea', 'open-science-desktop', 'Science', 'Open Science Desktop', 'Local-first, auditable AI research workflows', 'Open source; BYOK model/API costs', 'Model-agnostic desktop workbench for literature, code, notebooks, figures and reports with linked provenance and reproducible artifacts.', 'Desktop app; model-provider/API costs depend on the providers you connect. Local-first by default, with explicit approvals for high-risk actions.', 'Current', 'https://openedscience.com/', 'https://openedscience.com/', '2026-08-13', 'spreadsheet', 'approved')
on conflict (slug) do update set
  category = excluded.category,
  name = excluded.name,
  best_for = excluded.best_for,
  pricing = excluded.pricing,
  strengths = excluded.strengths,
  caveats = excluded.caveats,
  status = excluded.status,
  website_url = excluded.website_url,
  source_url = excluded.source_url,
  last_checked = excluded.last_checked,
  source_type = 'spreadsheet',
  moderation_status = 'approved';
